# Generated by Django 4.2.6 on 2023-10-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('Pname', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
