# Generated by Django 4.2.6 on 2023-10-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='itemid',
            new_name='iteid',
        ),
    ]
